# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doVB_pois <- function(y, rowi, coli, L, iter, a, b, alpha_z, beta_z, alpha_w, beta_w) {
    .Call(`_VBsNMF_doVB_pois`, y, rowi, coli, L, iter, a, b, alpha_z, beta_z, alpha_w, beta_w)
}

doVB_pois_s <- function(y, rowi, coli, L, iter, a, b, N1, alpha_z, beta_z, alpha_w, beta_w) {
    .Call(`_VBsNMF_doVB_pois_s`, y, rowi, coli, L, iter, a, b, N1, alpha_z, beta_z, alpha_w, beta_w)
}

