# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readRowsFromBinary <- function(filepath, rows, ncols) {
    .Call(`_VBsNMF_readRowsFromBinary`, filepath, rows, ncols)
}

readRowsFromBinary_umat <- function(filepath, rows, ncols) {
    .Call(`_VBsNMF_readRowsFromBinary_umat`, filepath, rows, ncols)
}

read_bin <- function(filepath_x, filepath_y, bag, n_dim) {
    .Call(`_VBsNMF_read_bin`, filepath_x, filepath_y, bag, n_dim)
}

writeBinaryVec <- function(data, filepath) {
    invisible(.Call(`_VBsNMF_writeBinaryVec`, data, filepath))
}

writeBinaryFile_umat <- function(data, filepath) {
    invisible(.Call(`_VBsNMF_writeBinaryFile_umat`, data, filepath))
}

doEM_pois <- function(y, rowi, coli, Nr, Nc, L, iter, a, b) {
    .Call(`_VBsNMF_doEM_pois`, y, rowi, coli, Nr, Nc, L, iter, a, b)
}

read_mtx <- function(readtxt, bag) {
    .Call(`_VBsNMF_read_mtx`, readtxt, bag)
}

lr_default <- function(t, delay, forgetting) {
    .Call(`_VBsNMF_lr_default`, t, delay, forgetting)
}

doVB_pois <- function(y, rowi, coli, Nr, Nc, L, iter, a, b) {
    .Call(`_VBsNMF_doVB_pois`, y, rowi, coli, Nr, Nc, L, iter, a, b)
}

doVB_pois_na <- function(y, rowi, coli, Nr, Nc, L, iter, a, b, wrow, wcol) {
    .Call(`_VBsNMF_doVB_pois_na`, y, rowi, coli, Nr, Nc, L, iter, a, b, wrow, wcol)
}

doVB_pois_s_mtx <- function(file_path, L, iter, subiter, a, b, N1, Nr, Nc, ns, delay, forgetting, display_progress) {
    .Call(`_VBsNMF_doVB_pois_s_mtx`, file_path, L, iter, subiter, a, b, N1, Nr, Nc, ns, delay, forgetting, display_progress)
}

